{% set name = "metatensor-core" %}
{% set version = "0.2.0.rc3" %}
{% set upstream_version = "0.2.0rc3" %}

package:
  name: python-{{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/metatensor_core-{{ upstream_version }}.tar.gz
  sha256: b32890e19d29c6eae5a3e44324463164048bad79d9c63224a79c8fe8884eb0ad

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    # Don't build metatensor-core, but use the already compiled `libmetatensor` package
    - METATENSOR_CORE_PYTHON_USE_EXTERNAL_LIB="ON"

requirements:
  build:
    # Nothing will be built but we need correct env to make pip happy
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - python
    - setuptools >=75
    - packaging >=23
    - pip
    - libmetatensor {{ version }}
  run:
    - python
    - libmetatensor {{ version }}
    - numpy

test:
  imports:
    - metatensor
  commands:
    - pip check
  requires:
    - python
    - pip

about:
  home: https://github.com/metatensor/metatensor
  summary: Python bindings for metatensor-core
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: docs.metatensor.org


extra:
  recipe-maintainers:
    - PicoCentauri
    - Luthaf
